# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - 3.6
    - 3.7
    - 3.8
    - 3.9

env:
    - version=without_numpy
    - version=with_numpy

#before_install:
#    - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
#     - bash miniconda.sh -b -p $HOME/miniconda
#     - export PATH="$HOME/miniconda/bin:$PATH"
#     - hash -r
#     - conda config --set always_yes yes --set changeps1 no
#     - conda update -q conda
#     - conda info -a

install:
    - if [[ $version == with_numpy ]]; then pip install numpy ; fi
    - python setup.py install
    - pip install codecov pytest

script:
    - cd tests
    - pytest
    - if [[ $version == with_numpy ]]; then coverage run --source=asteval test_asteval.py && coverage report -m ; fi

after_success:
    - if [[ $version == with_numpy ]]; then codecov ; fi
